cub: calculateCop_CUB.cu
	nvcc -O3 -o cub calculateCop_CUB.cu -lm -lnetcdf -Xcompiler -fopenmp -DBIG
cub_2: calculateCop_CUB_2.cu
	nvcc -O3 -o cub_2 calculateCop_CUB_2.cu -lm -lnetcdf -Xcompiler -fopenmp -DBIG
cub_batch: calculateCop_CUB_Batch.cu
	nvcc -O3 -o cub_batch calculateCop_CUB_Batch.cu -lm -lnetcdf -Xcompiler -fopenmp -DBIG

back_to_back: back_to_back.cu common.h
	nvcc -o back_to_back back_to_back.cu -lm
dev_segmented_cub_f32:

dev_segmented_cub_f32:

dev_segmented_cub_f32:

dev_segmented_cub_f32:

fast_seg_sort_f32:

fast_seg_sort_f32:

fast_seg_sort_f32:

fast_seg_sort_f32:

merg_back_to_back:

seg_sort_mgpu_f32:

seg_sort_mgpu:

seg_sort_mgpu:

seg_sort_mgpu:

clean: